apiVersion: v1
kind: Secret
metadata:
  name: tasky-secrets
  namespace: tasky
type: Opaque
data:
  MONGODB_URI_AUTH: 
  MONGODB_URI_USERS: 
  MONGODB_URI_PROJECTS: 
  MONGODB_URI_TASKS: 
  MONGODB_URI_TRACKER: 
  MONGODB_URI_INBOX: 
  JWT_SECRET: OWJkYjBjNGUtMjA5OS00ZjRlLWEzZWQtYTg0MDMyOWQ5NDNh
