apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: ghcr.io/tasky-io/task-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: '3003'
            - name: NODE_ENV
              value: 'production'
            - name: AUTH_SERVICE_URL
              value: 'http://auth-service:3000'
            - name: KAFKA_BROKER
              value: 'kafka-0.kafka.tasky.svc.cluster.local:9092'
            - name: KAFKA_CLIENT_ID
              value: 'task-service'
            - name: KAFKA_GROUP_ID
              value: 'tasky-task-group'
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tasky-secrets
                  key: MONGODB_URI_TASKS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tasky-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
