sonar.projectKey=tasky-user-service
sonar.organization=tasky-io-sliit
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
sonar.qualitygate.wait=true
